name: 💡 Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What should the feature be?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
    validations:
      required: false
