name: 💡 Feature Request
description: Schlage eine neue Funktion vor
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Welches Problem löst das?
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Gewünschte Lösung
    validations:
      required: true
